export const PAYMENT_MANUAL_NEW_PROOF = 'PAYMENT_MANUAL_NEW_PROOF';
export const PAYMENT_MANUAL_UPDATED = 'PAYMENT_MANUAL_UPDATED';
export const PAYMENT_MANUAL_TIMELINE_UPDATED =
  'PAYMENT_MANUAL_TIMELINE_UPDATED';
