{
 "title": "Fiers Artisans - Overview",
 "tags": [
  "fiers",
  "api",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus UP Targets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Targets Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum[5m])",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Current Targets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}