name: infrastructure
services:
  admin-web:
    image: infrastructure-admin-web
    command:
      - npm
      - run
      - dev
    container_name: fiers-admin-web
    depends_on:
      api:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: "1073741824"
    environment:
      NEXT_PUBLIC_API_BASE_PATH: /api/v1
      NEXT_PUBLIC_API_PORT: "3000"
      NEXT_PUBLIC_API_URL: ""
      NEXT_PUBLIC_DEFAULT_LOCALE: fr
      NODE_ENV: development
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - 'require(''http'').get(''http://localhost:3002'', (r) => { process.exit(r.statusCode < 500 ? 0 : 1) }).on(''error'', () => process.exit(1))'
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 50s
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 3002
        published: "3002"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/admin-web
        target: /app
        bind: {}
      - type: volume
        target: /app/node_modules
        volume: {}
      - type: volume
        target: /app/.next
        volume: {}
  api:
    image: infrastructure-api
    command:
      - npm
      - run
      - start:dev
    container_name: fiers-api
    depends_on:
      minio:
        condition: service_started
        required: true
      mongodb:
        condition: service_healthy
        required: true
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: "2147483648"
    environment:
      ADMIN_PHONE: "0700000000"
      ADMIN_PIN: "12345"
      ADMIN_WEB_API_URL: /api/v1
      APP_HOST: 0.0.0.0
      APP_PORT: "3000"
      APP_URL: http://localhost:3000
      CORS_ALLOW_LAN: "true"
      CORS_LAN_PORTS: 3000,3001,3002,5050,8080
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001,http://localhost:3002
      DATABASE_MONGO_URL: ""
      DATABASE_POSTGRES_URL: ""
      FCM_CLIENT_EMAIL: ""
      FCM_PRIVATE_KEY: ""
      FCM_PROJECT_ID: ""
      GRAFANA_ADMIN_PASSWORD: 8136d9f33b80d132d64b75fe
      JWT_ACCESS_EXPIRATION: 15m
      JWT_REFRESH_EXPIRATION: 30d
      JWT_REFRESH_SECRET: 1eccdd203e7f0786ce888fd2f98bc2141f540362b4a860ae77689ff51dd6c77d
      JWT_SECRET: da8e25b0562c051399cff53a369d4929b332533138383b34f6e02daf9b3cdd9b
      MINIO_ACCESS_KEY: fa61bf9219d8e571
      MINIO_BUCKET_DOCUMENTS: documents
      MINIO_BUCKET_MEDIA: media
      MINIO_BUCKET_PORTFOLIO: portfolio
      MINIO_ENDPOINT: minio
      MINIO_PORT: "9000"
      MINIO_PUBLIC_ENDPOINT: localhost
      MINIO_PUBLIC_PORT: "9002"
      MINIO_PUBLIC_USE_SSL: "false"
      MINIO_SECRET_KEY: 3a2fe89075a2d32301cc944651e91db1
      MINIO_USE_SSL: "false"
      MONGO_DB: fiers_artisans
      MONGO_HOST: mongodb
      MONGO_PASSWORD: 3fb24c1fb1aebd2eea70bc61a2f0e812
      MONGO_PORT: "27017"
      MONGO_USER: fiers_artisans
      NEXT_PUBLIC_API_BASE_PATH: /api/v1
      NEXT_PUBLIC_API_PORT: "3000"
      NEXT_PUBLIC_API_URL: ""
      NEXT_PUBLIC_DEFAULT_LOCALE: fr
      NODE_ENV: development
      OTP_BLOCK_DURATION_SECONDS: "900"
      OTP_DEV_INSPECTOR: "false"
      OTP_DEV_KEY: c45f0362e127ee097d2a1b855a5fe451c68b0cfb
      OTP_MAX_ATTEMPTS: "5"
      OTP_MAX_SENDS_PER_HOUR: "3"
      OTP_TTL_SECONDS: "300"
      PIN_ATTEMPT_WINDOW_SECONDS: "900"
      PIN_BLOCK_DURATION_SECONDS: "900"
      PIN_MAX_ATTEMPTS: "5"
      POSTGRES_DB: fiers_artisans
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: 312526c7677a8bd0c22008f3b1941ab8
      POSTGRES_PORT: "5432"
      POSTGRES_USER: fiers_artisans
      REDIS_HOST: redis
      REDIS_PASSWORD: 8ebe6d1a7bf864e21eb9b86db9132d1a
      REDIS_PORT: "6379"
      REDIS_URL: ""
      SMS_PROVIDER_ENABLED: "false"
      THROTTLE_LIMIT: "30"
      THROTTLE_TTL_MS: "60000"
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_PHONE_NUMBER: ""
      WAVE_API_KEY: ""
      WAVE_API_URL: https://api.wave.com/v1
      WAVE_MERCHANT_ID: ""
      WAVE_WEBHOOK_SECRET: 7c2dbd0565bf87caedc78acb5aecdc5e30d6b8620f8149ff
      WHATSAPP_API_TOKEN: ""
      WHATSAPP_API_URL: https://graph.facebook.com/v18.0
      WHATSAPP_OTP_TEMPLATE_NAME: fiers_artisans_otp
      WHATSAPP_PHONE_NUMBER_ID: ""
      WHATSAPP_PROVIDER_ENABLED: "true"
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - 'require(''http'').get(''http://localhost:3000/api/v1/health'', (r) => { process.exit(r.statusCode === 200 ? 0 : 1) })'
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/backend/src
        target: /app/src
        bind: {}
  grafana:
    container_name: fiers-grafana
    depends_on:
      prometheus:
        condition: service_started
        required: true
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 8136d9f33b80d132d64b75fe
    image: grafana/grafana
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3001"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
        volume: {}
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/infrastructure/monitoring/grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true
        bind: {}
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/infrastructure/monitoring/grafana/dashboards
        target: /var/lib/grafana/dashboards
        read_only: true
        bind: {}
  minio:
    command:
      - server
      - /data
      - --console-address
      - :9001
    container_name: fiers-minio
    environment:
      MINIO_ROOT_PASSWORD: 3a2fe89075a2d32301cc944651e91db1
      MINIO_ROOT_USER: fa61bf9219d8e571
    image: minio/minio
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 9000
        published: "9002"
        protocol: tcp
      - mode: ingress
        target: 9001
        published: "9003"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume: {}
  mongodb:
    container_name: fiers-mongodb
    environment:
      MONGO_INITDB_DATABASE: fiers_artisans
      MONGO_INITDB_ROOT_PASSWORD: 3fb24c1fb1aebd2eea70bc61a2f0e812
      MONGO_INITDB_ROOT_USERNAME: fiers_artisans
    healthcheck:
      test:
        - CMD
        - mongosh
        - --eval
        - db.adminCommand('ping')
        - -u
        - fiers_artisans
        - -p
        - 3fb24c1fb1aebd2eea70bc61a2f0e812
        - --authenticationDatabase
        - admin
        - --quiet
      timeout: 5s
      interval: 15s
      retries: 5
      start_period: 20s
    image: mongo:7
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 27017
        published: "27018"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
        volume: {}
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/infrastructure/mongodb/init.js
        target: /docker-entrypoint-initdb.d/init.js
        bind: {}
  postgres:
    container_name: fiers-postgres
    environment:
      POSTGRES_DB: fiers_artisans
      POSTGRES_PASSWORD: 312526c7677a8bd0c22008f3b1941ab8
      POSTGRES_USER: fiers_artisans
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER:-fiers_artisans} -d $${POSTGRES_DB:-fiers_artisans}
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgis/postgis:16-3.4
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5434"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/infrastructure/postgres/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        bind: {}
  prometheus:
    container_name: fiers-prometheus
    image: prom/prometheus
    networks:
      fiers-network: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/arthur/mes_projets_dev/Fiers_Artisants/infrastructure/monitoring/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
        bind: {}
      - type: volume
        source: prometheus_data
        target: /prometheus
        volume: {}
  redis:
    command:
      - sh
      - -c
      - redis-server --requirepass "8ebe6d1a7bf864e21eb9b86db9132d1a" --appendonly yes
    container_name: fiers-redis
    environment:
      REDIS_PASSWORD: 8ebe6d1a7bf864e21eb9b86db9132d1a
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - redis-cli -a "8ebe6d1a7bf864e21eb9b86db9132d1a" ping 2>/dev/null | grep -q PONG
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:7-alpine
    networks:
      fiers-network: null
    ports:
      - mode: ingress
        target: 6379
        published: "6380"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume: {}
networks:
  fiers-network:
    name: infrastructure_fiers-network
    driver: bridge
volumes:
  grafana_data:
    name: infrastructure_grafana_data
  minio_data:
    name: infrastructure_minio_data
  mongo_data:
    name: infrastructure_mongo_data
  postgres_data:
    name: infrastructure_postgres_data
  prometheus_data:
    name: infrastructure_prometheus_data
  redis_data:
    name: infrastructure_redis_data
